//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyInfoDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Hum_Sound
    {
        public System.DateTime event_date { get; set; }
        public Nullable<double> temp { get; set; }
        public Nullable<double> humidity { get; set; }
        public Nullable<double> sound { get; set; }
    }
}
